#!/usr/bin/env php
<?php
/**
 * happy coding!!!
 */

use DevHelper\Lib\Console\Application;

require_once './vendor/autoload.php';

!defined('BASE_PATH') && define('BASE_PATH', __DIR__);
!defined('SRC_PATH') && define('SRC_PATH', BASE_PATH . '/src');
!defined('PLUGIN_PATH') && define('PLUGIN_PATH', SRC_PATH . '/Plugin');
!defined('LIB_PATH') && define('LIB_PATH', SRC_PATH . '/Lib');
!defined('BIN_PATH') && define('BIN_PATH', BASE_PATH . '/bin');
!defined('CONFIG_PATH') && define('CONFIG_PATH', SRC_PATH . '/Config');

(new Application())->run();
